routing:
  paths:
    core-server:
      id: core-server
      prefix: /core
      pattern: /core
      url: http://15.164.70.24:3002
    playlist-server:
      id: playlist-server
      prefix: /pl
      pattern: /pl
      url: http://15.164.199.122:3001
    scheulder-server:
      id: scheulder-server
      prefix: /scheduler
      pattern: /scheduler
      url: http://15.164.199.122:3000